server:
  port: 8088
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auction_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tiger
  mail:
    host: smtp.qq.com
    port: 465
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB

mybatis-plus:
  type-aliases-package: com.yxq.auction.model

logging:
  level:
    com.yxq.auction.dao: debug
encryptJWTKey: yxq
accessTokenExpireTime: 300

